# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 8443, host: 443, host_ip: "127.0.0.1"
#  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  config.vm.provision "shell", inline: <<-SHELL
     yum install -y vim zip unzip git mercurial tmux
  SHELL

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
     curl -s "https://get.sdkman.io" | bash
     source "$HOME/.sdkman/bin/sdkman-init.sh"
     sdk i java 8u141-oracle
     sdk i ant 1.10.1
  SHELL

end

